name: Check and Merge PRs with Minor or Renovate Label

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - main

jobs:
  check-and-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set PR number
        id: set_pr_number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Check repository with Minor or Renovate label
        id: check_repo
        uses: actions/github-script@v6
        with:
          script: |
            const { repo } = context.repo;
            const octokit = github.rest;

            async function getRepoLabels() {
              try {
                const prNumber = process.env.PR_NUMBER;
                const prLabels = await octokit.pulls.get({
                  owner: repo.owner,
                  repo: repo.name,
                  pull_number: parseInt(prNumber)
                }).then(data => data.data);

                const hasMinorLabel = prLabels.some(label => label.name.toLowerCase() === 'minor');
                const hasRenovateLabel = prLabels.some(label => label.name.toLowerCase() === 'renovate');

                return {
                  hasMinorOrRenovate: hasMinorLabel || hasRenovateLabel
                };
              } catch (error) {
                console.error('Error fetching PR labels:', error.message);
                throw error;
              }
            }

            const repoInfo = await getRepoLabels();

            if (repoInfo.hasMinorOrRenovate) {
              console.log(`Found open PR with Minor or Renovate label`);
              
              // Merge the PR
              await octokit.rest.pulls.merge({
                owner: repo.owner,
                repo: repo.name,
                pull_number: parseInt(process.env.PR_NUMBER),
                commit_title: 'Auto-merge PR with Minor/Renovate label',
                sha: process.env.GITHUB_SHA
              });

              console.log(`Merged PR #${process.env.PR_NUMBER}`);
            } else {
              console.log(`No open PRs with Minor or Renovate label`);
            }
