name: Check Repository with Minor or Renovate Label on PR

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        default: ''
  check_run:
    types: [completed]

jobs:
  check-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set PR number
        id: set_pr_number
        run: echo "PR_NUMBER=${{ inputs.pr_number }}" >> $GITHUB_ENV

      - name: Check repository with Minor or Renovate label
        id: check_repo
        uses: actions/github-script@v6
        with:
          script: |
            const { repo } = context.repo;
            const octokit = github.rest;
            const prNumber = process.env.PR_NUMBER;

            async function getRepoLabels() {
              try {
                const prLabels = await octokit.pulls.getLabels({
                  owner: repo.owner,
                  repo: repo.name,
                  pull_number: prNumber
                }).then(data => data.data);

                const hasMinorLabel = prLabels.some(label => label.name.toLowerCase() === 'minor');
                const hasRenovateLabel = prLabels.some(label => label.name.toLowerCase() === 'renovate');

                return {
                  hasMinorOrRenovate: hasMinorLabel || hasRenovateLabel
                };
              } catch (error) {
                console.error('Error fetching PR labels:', error.message);
                throw error;
              }
            }

            const repoInfo = await getRepoLabels();

            if (repoInfo.hasMinorOrRenovate) {
              console.log(`PR #${prNumber} has either Minor or Renovate label`);
              
              // Example: Send a notification to a Slack channel
              await octokit.rest.issues.create({
                owner: repo.owner,
                repo: repo.name,
                title: 'Repository with Minor or Renovate Label',
                body: `This pull request has either Minor or Renovate label:\n\nPR #${prNumber}`
              });
            } else {
              console.log(`PR #${prNumber} does not have either Minor or Renovate label`);
            }
